# Generated by Django 5.0.6 on 2026-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(help_text='Unique student identification number', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Student's full name as it appears on official documents", max_length=255)),
                ('national_id', models.CharField(help_text='National ID number (e.g., 67-123456X78)', max_length=50, unique=True)),
                ('department', models.CharField(choices=[('EDUCATION', 'Education'), ('SCIENCES', 'Sciences'), ('ARTS', 'Arts & Humanities'), ('COMMERCE', 'Commerce'), ('AGRICULTURE', 'Agriculture'), ('VOCATIONAL', 'Vocational Studies')], help_text='Academic department', max_length=50)),
                ('year_of_study', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Postgraduate')], default=1, help_text='Current year of study')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text="Student's gender", max_length=10)),
                ('photo', models.ImageField(blank=True, help_text="Student's passport-style photograph", null=True, upload_to='student_photos/')),
                ('qr_code', models.ImageField(blank=True, editable=False, help_text='Auto-generated QR code containing student number', null=True, upload_to='qr_codes/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('email', models.EmailField(blank=True, help_text="Student's email address", max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address', null=True)),
                ('next_of_kin_name', models.CharField(blank=True, help_text='Next of kin full name', max_length=255, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, help_text='Next of kin contact number', max_length=20, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, help_text='Relationship to next of kin', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the student is currently active')),
                ('is_registered', models.BooleanField(default=False, help_text='Whether the student has completed registration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the student record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the student record was last updated')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_number'], name='students_student_fa2474_idx'), models.Index(fields=['national_id'], name='students_nationa_87c610_idx'), models.Index(fields=['department'], name='students_departm_33c447_idx'), models.Index(fields=['year_of_study'], name='students_year_of_842695_idx')],
            },
        ),
    ]
