# Generated by Django 5.0.6 on 2026-03-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the hostel (e.g., 'Main Hostel', 'Girls Hostel')", max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], default='MIXED', help_text='Gender designation for the hostel', max_length=10)),
                ('capacity', models.IntegerField(default=0, help_text='Total number of students the hostel can accommodate')),
                ('description', models.TextField(blank=True, help_text='Description of the hostel facilities', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the hostel is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the hostel was added to the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the hostel information was last updated')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'db_table': 'hostels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text="Room number/identifier (e.g., '101', 'A101')", max_length=20)),
                ('capacity', models.IntegerField(default=1, help_text='Maximum number of students the room can accommodate')),
                ('floor', models.CharField(blank=True, help_text='Floor level (optional)', max_length=10, null=True)),
                ('room_type', models.CharField(blank=True, help_text="Room type (e.g., 'Single', 'Double', 'Suite')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the room is available for allocation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the room was added to the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the room information was last updated')),
                ('hostel', models.ForeignKey(help_text='Hostel where the room is located', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodation.hostel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['hostel__name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2'), ('FULL_YEAR', 'Full Academic Year'), ('SHORT_TERM', 'Short Term')], default='FULL_YEAR', help_text='Accommodation period', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITING_LIST', 'Waiting List'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current application status', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True, help_text='Date when the application was submitted')),
                ('decision_date', models.DateTimeField(blank=True, help_text='Date when the application was approved/rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requirements', null=True)),
                ('rejection_reason', models.CharField(blank=True, help_text='Reason for rejection (if applicable)', max_length=255, null=True)),
                ('waiting_list_position', models.IntegerField(default=0, help_text='Position on waiting list (0 if not on waiting list)')),
                ('check_in_date', models.DateTimeField(blank=True, help_text='Actual check-in date', null=True)),
                ('check_out_date', models.DateTimeField(blank=True, help_text='Actual check-out date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the application was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the application was last updated')),
                ('student', models.ForeignKey(help_text='Student applying for accommodation', on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_applications', to='students.student')),
                ('hostel', models.ForeignKey(blank=True, help_text='Preferred hostel (assigned on approval if not specified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accommodation.hostel')),
                ('room', models.ForeignKey(blank=True, help_text='Assigned room (set on approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accommodation.room')),
            ],
            options={
                'verbose_name': 'Accommodation Application',
                'verbose_name_plural': 'Accommodation Applications',
                'db_table': 'accommodation_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hostel', 'room_number'], name='rooms_hostel__fba053_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='rooms_is_acti_b7cb02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='accommodationapplication',
            index=models.Index(fields=['student', 'status'], name='accommodati_student_10adfa_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationapplication',
            index=models.Index(fields=['status', 'application_date'], name='accommodati_status_3f9298_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodationapplication',
            index=models.Index(fields=['hostel', 'status'], name='accommodati_hostel__037891_idx'),
        ),
    ]
