from rest_framework import serializers
from .models import Student, Gender, YearOfStudy, Department


class StudentSerializer(serializers.ModelSerializer):
    """Serializer for Student model"""
    department_display = serializers.CharField(
        source='get_department_display',
        read_only=True
    )
    year_of_study_display = serializers.CharField(
        source='get_year_of_study_display',
        read_only=True
    )
    gender_display = serializers.CharField(
        source='get_gender_display',
        read_only=True
    )
    qr_code_url = serializers.SerializerMethodField()
    photo_url = serializers.SerializerMethodField()
    id_card_ready = serializers.BooleanField(read_only=True)
    
    class Meta:
        model = Student
        fields = [
            'id', 'student_number', 'full_name', 'national_id',
            'department', 'department_display',
            'year_of_study', 'year_of_study_display',
            'gender', 'gender_display',
            'photo', 'photo_url',
            'qr_code', 'qr_code_url',
            'date_of_birth', 'email', 'phone_number', 'address',
            'next_of_kin_name', 'next_of_kin_phone', 'next_of_kin_relationship',
            'is_active', 'is_registered',
            'created_at', 'updated_at',
            'has_photo', 'has_qr_code', 'id_card_ready'
        ]
        read_only_fields = [
            'id', 'created_at', 'updated_at',
            'qr_code', 'qr_code_url',
            'has_photo', 'has_qr_code', 'id_card_ready'
        ]
    
    def get_qr_code_url(self, obj):
        """Get absolute URL for QR code image"""
        if obj.qr_code:
            request = self.context.get('request')
            if request:
                return request.build_absolute_uri(obj.qr_code.url)
            return obj.qr_code.url
        return None
    
    def get_photo_url(self, obj):
        """Get absolute URL for photo image"""
        if obj.photo:
            request = self.context.get('request')
            if request:
                return request.build_absolute_uri(obj.photo.url)
            return obj.photo.url
        return None
    
    def validate_student_number(self, value):
        """Validate student number format"""
        # Student number should be alphanumeric
        if not value.replace('-', '').replace('/', '').isalnum():
            raise serializers.ValidationError(
                "Student number should contain only letters, numbers, hyphens and slashes."
            )
        return value
    
    def validate_national_id(self, value):
        """Validate national ID format (Zimbabwean format)"""
        # Zimbabwean national ID format: XX-XXXXXX-X##
        import re
        pattern = r'^\d{2}-\d{6}[A-Z]\d{2}$'
        if not re.match(pattern, value.upper()):
            raise serializers.ValidationError(
                "National ID should be in format: 67-123456X78"
            )
        return value.upper()
    
    def create(self, validated_data):
        """Create student - QR code will be auto-generated by model save method"""
        return super().create(validated_data)


class StudentCreateSerializer(serializers.ModelSerializer):
    """Serializer for creating a new student with minimal required fields"""
    class Meta:
        model = Student
        fields = [
            'student_number', 'full_name', 'national_id',
            'department', 'year_of_study', 'gender',
            'email', 'phone_number'
        ]


class StudentUpdateSerializer(serializers.ModelSerializer):
    """Serializer for updating student information"""
    class Meta:
        model = Student
        fields = [
            'full_name', 'national_id', 'department', 'year_of_study',
            'gender', 'date_of_birth', 'email', 'phone_number', 'address',
            'next_of_kin_name', 'next_of_kin_phone', 'next_of_kin_relationship',
            'is_active', 'is_registered'
        ]


class StudentPhotoUploadSerializer(serializers.ModelSerializer):
    """Serializer for uploading student photo"""
    class Meta:
        model = Student
        fields = ['photo']


class StudentListSerializer(serializers.ModelSerializer):
    """Lightweight serializer for listing students"""
    department_display = serializers.CharField(
        source='get_department_display',
        read_only=True
    )
    year_of_study_display = serializers.CharField(
        source='get_year_of_study_display',
        read_only=True
    )
    
    class Meta:
        model = Student
        fields = [
            'id', 'student_number', 'full_name', 'department',
            'department_display', 'year_of_study', 'year_of_study_display',
            'gender', 'email', 'is_active', 'is_registered',
            'has_photo', 'has_qr_code', 'created_at'
        ]


class QRCodeDataSerializer(serializers.Serializer):
    """Serializer for QR code data structure"""
    student_number = serializers.CharField()
    full_name = serializers.CharField()
    department = serializers.CharField()
    institution = serializers.CharField()
