# Generated by Django 5.0.6 on 2026-03-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], help_text='Type of meal (breakfast, lunch, dinner)', max_length=20)),
                ('date', models.DateField(help_text='Date of the meal')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the attendance was recorded')),
                ('scanner_device', models.CharField(blank=True, help_text='Scanner device identifier (e.g., device ID, terminal name)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special dietary requirements', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('student', models.ForeignKey(help_text='Student who attended the meal', on_delete=django.db.models.deletion.CASCADE, related_name='dining_attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Dining Attendance',
                'verbose_name_plural': 'Dining Attendances',
                'db_table': 'dining_attendances',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'meal_type', 'date'], name='dining_atte_student_37a9ca_idx'), models.Index(fields=['date', 'meal_type'], name='dining_atte_date_bdd9b8_idx'), models.Index(fields=['timestamp'], name='dining_atte_timesta_5514e2_idx')],
                'unique_together': {('student', 'meal_type', 'date')},
            },
        ),
    ]
