# Generated by Django 5.0.6 on 2026-03-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(help_text='Student number (stored for offline operation)', max_length=20)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], help_text='Type of meal', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when scan was recorded offline')),
                ('device_id', models.CharField(help_text='Device identifier that recorded the scan', max_length=100)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCING', 'Syncing...'), ('SYNCED', 'Synced'), ('FAILED', 'Sync Failed')], default='PENDING', help_text='Current sync status', max_length=20)),
                ('sync_attempts', models.IntegerField(default=0, help_text='Number of sync attempts')),
                ('last_sync_attempt', models.DateTimeField(blank=True, help_text='Last sync attempt timestamp', null=True)),
                ('sync_error', models.TextField(blank=True, help_text='Error message from last sync attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the offline scan was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the offline scan was last updated')),
                ('attendance_record', models.ForeignKey(blank=True, help_text='Linked attendance record after successful sync', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_scan_source', to='dining.diningattendance')),
            ],
            options={
                'verbose_name': 'Offline Scan',
                'verbose_name_plural': 'Offline Scans',
                'db_table': 'offline_scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_status'], name='offline_sca_sync_st_3ed1f9_idx'), models.Index(fields=['student_number'], name='offline_sca_student_0d46ee_idx'), models.Index(fields=['meal_type'], name='offline_sca_meal_ty_052bd7_idx'), models.Index(fields=['created_at'], name='offline_sca_created_ed374c_idx')],
            },
        ),
    ]
